### PR TITLE
Remove non-prefixed methods

### PR DESCRIPTION
**Pull request by douglashill**
The non-prefixed methods were broken in commit 7f2fec8a4df2 in October 2013.

This pull request fixes this, so it successfully compiles with `MTDATES_NO_PREFIX` enabled. I fixed it because it was broken; I do not advocate using these methods.

The fact that nobody has complained in 18 months suggests it would be fine to remove the non-prefixed methods, but I leave that up to you.

### CODE REVIEW

**Comment by yas375** [comment]
Indeed! :+1: Good reason to drop non-prefixed methods ;)

**Comment by douglashill** [comment]
If you like, I can add removing non-prefixed methods to this pull request.

**Comment by yas375** [comment]
@douglashill I'm not maintainer of the lib. Probably @atomkirk is the right person to answer this ;)

**Comment by atomkirk** [comment]
yeah, I'm gonna remove the non-prefixed methods. I can't do it till this evening. If you submit a pull request with them all removed before then I'll merge it immediately

**Comment by atomkirk** [comment]
well crap, I didn't get the e-mail for your update, so I removed them myself. Sorry about that, thanks for helping. I've published it as 1.0.2.

**Pull request closed without merging**
